### ISSUE TITLE
Set up Travis to build book and deploy to Netlify

### ISSUE THREAD

**Issue by hammer** [hammerlab/t-cell-data#13]
Yihue provides some details at https://bookdown.org/yihui/bookdown/github.html

**Comment by hammer** [comment]
The https://github.com/ropenscilabs/drake-manual has a `build.R` that copies over images that I want to steal

**Comment by hammer** [comment]
Can possibly benefit from 
https://ropenscilabs.github.io/tic/

**Comment by hammer** [comment]
Another example that manipulates the favicon: 
https://github.com/jeroenjanssens/data-science-at-the-command-line/blob/master/.travis.yml

**Comment by hammer** [comment]
Some twitter discussions on this topic: 
https://mobile.twitter.com/apreshill/status/1058096798500179968

**Comment by hammer** [comment]
Well, the Netlify part was easy: https://tcelldata.hammerlab.org.

Spent an hour or so thinking/reading about the best way to handle the Travis part today and still pretty stumped. Going to start a `test-book` repo to see if I can get it working.

The general idea is going to be:

1. Install and validate availability of [Docker containers](https://docs.travis-ci.com/user/docker/), [R packages](https://docs.travis-ci.com/user/languages/r/), and other [dependencies](https://docs.travis-ci.com/user/installing-dependencies/) we need
1. Build the book into `_book`
1. Move images into `_book`
1. Copy `_book` contents to a separate branch `book_contents` (or something) (can use the [GitHub Pages deployment](https://docs.travis-ci.com/user/deployment/pages/) to do it)
1. Delete `_book`

Serving the book should be pretty trivial: just point Netlify to the `book_contents` branch.

To speed up the build check out [caching](https://docs.travis-ci.com/user/caching/) and using [build stages](https://docs.travis-ci.com/user/build-stages/) to build chapters in parallel.

**Comment by armish** [comment]
FWIW: Travis can either throttle network access or choke on the build if the analyses become heavier and heavier. GCloud's Cloud Build would allow more flexibility here and given the frequency of updates, we should mostly be in its free tier:

https://cloud.google.com/cloud-build/docs/create-custom-build-steps

Looks like the only bottleneck is to get a Docker image/file ready.

**Comment by hammer** [comment]
@armish thanks for the pointer! I like that they offer parallelized builds on their free tier. I'm a little concerned that they don't seem to have much support for R builds out of the box. I'll probably try Travis w/ a small project and see if we hit any limits before trying out Google's offering.

**Comment by hammer** [comment]
## Bookdown project template

### `_bookdown.yml`
```
book_filename: "test-book"
delete_merged_file: true
language:
  ui:
    chapter_name: "Chapter "
```

### `_output.yml`:
```
bookdown::gitbook:
  css: style.css
  config:
    toc:
      before: |
        <li><a href="./">A Minimal Book Example</a></li>
      after: |
        <li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
    download: ["pdf", "epub"]
bookdown::pdf_book:
  includes:
    in_header: preamble.tex
  latex_engine: xelatex
  citation_package: natbib
  keep_tex: yes
bookdown::epub_book: default
```

### Build
When we built the book (`Ctrl+Shift+B`), we get:
- `packages.bib`
- `_book/`
- `_bookdown_files/`

**Comment by hammer** [comment]
Preparing for something horrible when I try to install Bioconductor packages with Travis: https://github.com/r-lib/devtools/issues/1254

**Comment by hammer** [comment]
Working nicely! Package and data caches mean builds are only 6 minutes, 30 seconds, which is pretty reasonable.
